# Generated by Django 5.1 on 2024-08-28 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revaluationrequest',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_requests', to='exam_management.answersheet'),
        ),
    ]
