# Generated by Django 5.1 on 2024-08-28 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0003_alter_evaluation_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='revaluation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='revaluationrequest',
            unique_together={('student', 'answer_sheet')},
        ),
    ]
